[package]
name = "client"
edition = "2021"

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }

eframe = "0.29.1"
reqwest = { version = "0.12.9", features = ["json", "blocking"] }