[package]
name = "server"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }

rusqlite = "0.32.1"
warp = "0.3.7"
tokio = { version = "1.41.1", features = ["full"] }